# Generated by Django 4.2.13 on 2024-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordfile',
            name='search_word',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
