# Generated by Django 4.2.13 on 2024-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wordfile_search_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordfile',
            name='word_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='wordfile',
            name='search_word',
            field=models.CharField(default='', max_length=255),
        ),
    ]
